"""
Channel Type Module
===================
Contains the ChannelType mapping of sequential integers to str type representations. Inverse of the ChannelType generated by `ndi_schema<https://>`_.
"""
from .schema.ChannelType import ChannelType as ChannelType_schema
from .utils import generate_tuple_analog


ChannelType = generate_tuple_analog(ChannelType_schema)
