"""
Channel Type Module
===================
Contains the ChannelType mapping of sequential integers to str type representations. Inverse of the ChannelType generated by `ndi_schema<https://>`_.
"""


# TODO: make immutable somehow
ChannelType = {
    0: 'analog_in',
    1: 'analog_out',
    2: 'digital_in',
    3: 'digital_out',
    4: 'time',
    5: 'auxiliary',
    6: 'event',
    7: 'mark'
}
