"""
Channel Type Module
===================
Contains the ChannelType mapping of sequential integers to str type representations. Inverse of the ChannelType generated by `ndi_schema<https://>`_.
"""

ChannelType = (
    'analog_in',
    'analog_out',
    'digital_in',
    'digital_out',
    'time',
    'auxiliary',
    'event',
    'mark'
)
