from .ndi_object import NDI_Object
import ndi.schema.Channel as build_channel
from ndi.schema.ClockType import ClockType as build_clock_type
from ndi.schema.ChannelType import ChannelType as build_channel_type
from .channel_type import ChannelType
from .clock_type import ClockType

class Channel(NDI_Object):
    """A flatbuffer interface for channels.
    
    .. currentmodule:: ndi.ndi_object
    Inherits from the :class:`NDI_Object` abstract class.
    """

    # TODO: require daq_system_id after implementing DaqReaders
    def __init__(self, name, number, type_, source_file, epoch_id, probe_id, daq_system_id='', id_=None, clock_type='no_time',):
        """Channel constructor: initializes with fields defined in `ndi_schema <https://>`_'s Channel table. For use when creating a new Channel instance from scratch.
        ::
            new_channel = Channel(**fields)
        
        :param name: Abbreviated type with number (e.g. ai21, do3, aux13).
        :type name: str
        :param number: [description]
        :type number: int
        :param type_: One of the types defined in :mod:`ndi.channel_type`.
        :type type_: str
        :param source_file: [description]
        :type source_file: str
        :param epoch_id: [description]
        :type epoch_id: str
        :param probe_id: [description]
        :type probe_id: str
        :param daq_system_id: defaults to '<empty_string>'
        :type daq_system_id: str, optional
        :type id_: str, optional
        :param clock_type: defaults to 'no_time'
        :type clock_type: str, optional
        .. currentmodule:: ndi.channel
        :rtype: :class:`Channel`
        """
        super().__init__(id_)
        self.name = name
        self.number = number
        self.type = type_
        self.clock_type = clock_type
        self.source_file = source_file
        self.epoch_id = epoch_id
        self.probe_id = probe_id
        self.daq_system_id = daq_system_id

    @classmethod
    def from_flatbuffer(cls, flatbuffer):
        """Alternate Channel constructor. For use whan initializing from a flatbuffer bytearray.
        ::
            reconstructed_channel = Channel.from_flatbuffer(fb)
        
        :type flatbuffer: bytearray
        .. currentmodule:: ndi.channel
        :rtype: :class:`Channel`
        """
        channel = build_channel.Channel.GetRootAsChannel(flatbuffer, 0)
        return cls._reconstruct(channel)

    @classmethod
    def _reconstruct(cls, channel):
        """Alternate Channel constructor. For use whan initializing from a flatbuffer generated class instance.
        
        :param channel: Channel object created from class generated by `ndi_schema<https://>`_
        :type channel: ndi.schema.Channel.Channel
        .. currentmodule:: ndi.channel
        :rtype: :class:`Channel`
        """
        return cls(id_=channel.Id().decode('utf8'),
                   name=channel.Name().decode('utf8'),
                   number=channel.Number(),
                   type_=ChannelType[channel.Type()],
                   clock_type=ClockType[channel.ClockType()],
                   source_file=channel.SourceFile().decode('utf8'),
                   epoch_id=channel.EpochId().decode('utf8'),
                   probe_id=channel.ProbeId().decode('utf8'),
                   daq_system_id=channel.DaqSystemId().decode('utf8'))

    def _build(self, builder):
        """.. currentmodule:: ndi.ndi_object
        Called in NDI_Object.serialize() as part of flatbuffer bytearray generation from Channel instance.
        
        :param builder: Builder class in flatbuffers module.
        :type builder: flatbuffers.Builder
        """
        id_ = builder.CreateString(self.id)
        name = builder.CreateString(self.name)
        source_file = builder.CreateString(self.source_file)
        epoch_id = builder.CreateString(self.epoch_id)
        probe_id = builder.CreateString(self.probe_id)
        daq_system_id = builder.CreateString(self.daq_system_id)

        build_channel.ChannelStart(builder)
        build_channel.ChannelAddId(builder, id_)
        build_channel.ChannelAddName(builder, name)
        build_channel.ChannelAddNumber(builder, self.number)
        build_channel.ChannelAddType(
            builder, getattr(build_channel_type, self.type))
        build_channel.ChannelAddClockType(
            builder, getattr(build_clock_type, self.clock_type))
        build_channel.ChannelAddSourceFile(builder, source_file)
        build_channel.ChannelAddEpochId(builder, epoch_id)
        build_channel.ChannelAddProbeId(builder, probe_id)
        build_channel.ChannelAddDaqSystemId(builder, daq_system_id)
        return build_channel.ChannelEnd(builder)
