"""
Clock Type Module
===================
Contains the ClockType mapping of sequential integers to str type representations. Inverse of the ClockType generated by `ndi_schema<https://>`_.
"""


# TODO: make immutable somehow
ClockType = {
    0: 'utc',
    1: 'approx_utc',
    2: 'exp_global_time',
    3: 'approx_exp_global_time',
    4: 'dev_global_time',
    5: 'approx_dev_global_time',
    6: 'dev_local_time',
    7: 'no_time',
    8: 'inherited'
}
