"""
Clock Type Module
===================
Contains the ClockType mapping of sequential integers to str type representations. Inverse of the ClockType generated by `ndi_schema<https://>`_.
"""
from .schema.ClockType import ClockType as ClockType_schema
from .utils import generate_tuple_analog


ClockType = generate_tuple_analog(ClockType_schema)
