"""
Clock Type Module
===================
Contains the ClockType mapping of sequential integers to str type representations. Inverse of the ClockType generated by `ndi_schema<https://>`_.
"""

ClockType = (
    'utc',
    'approx_utc',
    'exp_global_time',
    'approx_exp_global_time',
    'dev_global_time',
    'approx_dev_global_time',
    'dev_local_time',
    'no_time',
    'inherited'
)
