from __future__ import annotations
import ndi.types as T
from .ndi_object import NDI_Object
import ndi.schema.Epoch as build_epoch


class Epoch(NDI_Object):
    """
    A flatbuffer interface for epochs.

    .. currentmodule:: ndi.ndi_object

    Inherits from the :class:`NDI_Object` abstract class.
    """
    # TODO: require daq_system_id after implementing DaqReaders

    def __init__(
        self, 
        daq_system_id: T.NdiId = None, 
        experiment_id: T.NdiId = None, 
        id_: T.NdiId = None
    ) -> None:
        """Epoch constructor: initializes with fields defined in `ndi_schema <https://>`_'s Epoch table. For use when creating a new Epoch instance from scratch.
        ::
            new_epoch = Epoch(**fields)

        :param daq_system_id: defaults to ''
        :type daq_system_id: str, optional
        :param id_: defaults to None
        :type id_: str, optional
        """
        super().__init__(id_)
        self.daq_system_id = daq_system_id
        self.experiment_id = experiment_id

    @classmethod
    def from_flatbuffer(cls, flatbuffer: bytes) -> Epoch:
        """Alternate Epoch constructor. For use whan initializing from a flatbuffer bytearray.
        ::
            reconstructed_epoch = Epoch.from_flatbuffer(fb)

        :type flatbuffer: bytearray

        .. currentmodule:: ndi.epoch

        :rtype: :class:`Epoch`
        """
        epoch = build_epoch.Epoch.GetRootAsEpoch(flatbuffer, 0)
        return cls._reconstruct(epoch)

    @classmethod
    def _reconstruct(cls, epoch: T.Epoch_schema) -> Epoch:
        """Alternate Epoch constructor. For use whan initializing from a flatbuffer generated class instance.

        :param epoch: Epoch object created from class generated by `ndi_schema<https://>`_
        :type epoch: ndi.schema.Epoch.Epoch

        .. currentmodule:: ndi.epoch

        :rtype: :class:`Epoch`
        """
        return cls(
            id_=T.NdiId(epoch.Id().decode('utf8')),
            daq_system_id=T.NdiId(epoch.DaqSystemId().decode('utf8')),
            experiment_id=T.NdiId(epoch.ExperimentId().decode('utf8')),
        )

    def _build(self, builder: T.Builder) -> T.BuildOffset:
        """.. currentmodule:: ndi.ndi_object

        Called in NDI_Object.serialize() as part of flatbuffer bytearray generation from Epoch instance.

        :param builder: Builder class in flatbuffers module.
        :type builder: flatbuffers.Builder
        """
        id_ = builder.CreateString(self.id)
        daq_system_id = builder.CreateString(self.daq_system_id)
        experiment_id = builder.CreateString(self.experiment_id)

        build_epoch.EpochStart(builder)
        build_epoch.EpochAddId(builder, id_)
        build_epoch.EpochAddDaqSystemId(builder, daq_system_id)
        build_epoch.EpochAddExperimentId(builder, experiment_id)
        return build_epoch.EpochEnd(builder)

    def update(
        self, 
        daq_system_id: T.NdiId = None, 
        experiment_id: T.NdiId = None, 
    ) -> None:
        if daq_system_id: self.daq_system_id = daq_system_id
        if experiment_id: self.experiment_id = experiment_id

        self.ctx.update(self)