from __future__ import annotations
import ndi.types as T
from abc import ABC, abstractmethod
import flatbuffers
from uuid import uuid4


class Flatbuffer_Object(ABC):
    """
    Abstract class for NDI flatbuffer interfaces.
    Child classes of :class:`NDI_Object` are wrappers for the classes generated by `ndi_schema <>`_ and serve as simplified interfaces for quickly converting between ndi objects and flatbuffer bytearrays.
    """
    @abstractmethod
    def __init__(self, id_: T.Optional[T.NdiId]):
        """NDI_Object constructor: initializes id property.
        op8
        :param id_: A unique id.
        :type id_: str, optional
        """
        self.id = id_ or T.NdiId(uuid4().hex)

    # Flatbuffer Methods for converting to and from flatbuffers
    @classmethod
    @abstractmethod
    def from_flatbuffer(cls, flatbuffer: bytes):
        """
        It should create an instance of the class inheriting from :class:`NDI_Object` from a given flatbuffer of the correct schema.
        ::
            flatbuffer_object = GetRootAsNDIObject(flatbuffer, 0)
            return cls._reconstruct(flatbuffer_object)

        :return: An instance of the child class.
        """
        pass

    @classmethod
    @abstractmethod
    def _reconstruct(cls, flatbuffer_object) -> T.NdiObject:
        """
        Creates ndi_object instance from flatbuffer object 

            return cls(property=ndi_object.Property())
        """
        pass

    @abstractmethod
    def _build(self, builder: T.Builder) -> T.BuildOffset:
        """
        Builds flatbuffer of object instance

            NDIObjectStart(builder)

            NDIObjectAddProperty(builder, property)

            return NDIObjectEnd(builder)
        """
        pass

    def serialize(self) -> bytearray:
        """
        Builds a flatbuffer from the :class:`NDI_Object` instance.

        :rtype: bytearray
        """
        builder = flatbuffers.Builder(0)
        ndi_object = self._build(builder)
        builder.Finish(ndi_object)
        return builder.Output()

    def __eq__(self, ndi_object) -> bool:
        return self.serialize() == ndi_object.serialize()


