from __future__ import annotations
import ndi.types as T
from abc import ABC, abstractmethod
import flatbuffers
from uuid import uuid4
from .document import Document


class NDI_Object(ABC):
    """
    Abstract class for NDI flatbuffer interfaces.
    Child classes of :class:`NDI_Object` are wrappers for the classes generated by `ndi_schema <>`_ and serve as simplified interfaces for quickly converting between ndi objects and flatbuffer bytearrays.
    """

    DOCUMENT_TYPE = ''

    @abstractmethod
    def __init__(self,  id_: T.Optional[T.NdiId]):
        """NDI_Object constructor: initializes id property.
        op8
        :param id_: A unique id.
        :type id_: str, optional
        """
        self.document = Document()
    
    @property
    def id(self):
        return self.document.id

    @property
    def metadata(self):
        return self.document.metadata
    @metadata.setter
    def metadata(self, new_metadata):
        self.document.metadata = new_metadata

    @property
    def dependencies(self):
        return self.document.dependencies
    @dependencies.setter
    def dependencies(self, dependencies):
        self.document.dependencies = dependencies

    def __eq__(self, ndi_object) -> bool:
        return self.document.serialize() == ndi_object.document.serialize()

    def add_data_property(self, key, value):
        self.document.data[key] = value

    def __getattribute__(self, key):
        try:
            return object.__getattribute__(self, 'document').data[key]
        except (KeyError, AttributeError):
            return object.__getattribute__(self, key)

    def __setattr__(self, key, value):
        try:
            object.__getattribute__(self, 'document').data[key] = value
        except (KeyError, AttributeError):
            object.__setattr__(self, key, value)


