from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import ndi.type as T

from abc import ABC, abstractmethod
import flatbuffers
from uuid import uuid4


class NDI_Object(ABC):
    """
    Abstract class for NDI flatbuffer interfaces.
    Child classes of :class:`NDI_Object` are wrappers for the classes generated by `ndi_schema <>`_ and serve as simplified interfaces for quickly converting between ndi objects and flatbuffer bytearrays.
    """
    @abstractmethod
    def __init__(self, id_: T.Optional[T.NdiId]):
        """NDI_Object constructor: initializes id property.
        op8
        :param id_: A unique id.
        :type id_: str, optional
        """
        self.id = id_ or uuid4().hex

    # Flatbuffer Methods for converting to and from flatbuffers
    @classmethod
    @abstractmethod
    def from_flatbuffer(cls, flatbuffer: bytearray):
        """
        It should create an instance of the class inheriting from :class:`NDI_Object` from a given flatbuffer of the correct schema.
        ::
            flatbuffer_object = GetRootAsNDIObject(flatbuffer, 0)
            return cls._reconstruct(flatbuffer_object)

        :return: An instance of the child class.
        """
        pass

    @classmethod
    @abstractmethod
    def _reconstruct(cls, flatbuffer_object: T.Schema) -> T.NdiObject:
        """
        Creates ndi_object instance from flatbuffer object 

            return cls(property=ndi_object.Property())
        """
        pass

    @classmethod
    def _reconstructList(cls, flatbuffer_object_parent: T.Schema) -> T.List[T.NdiObject]:
        """
        Creates ndi_object instances for flatbuffer objects in a vector 
        """
        return [
            cls._reconstruct(
                getattr(flatbuffer_object_parent, f'{cls.__name__}s')(i))
            for i in range(getattr(flatbuffer_object_parent, f'{cls.__name__}sLength')())
        ]

    @abstractmethod
    def _build(self, builder: T.Builder):
        """
        Builds flatbuffer of object instance

            NDIObjectStart(builder)

            NDIObjectAddProperty(builder, property)

            return NDIObjectEnd(builder)
        """
        pass

    @staticmethod
    def _buildStringVector(builder: T.Builder, strings: T.List[str]):
        """
        Builds flatbuffer vector from list of strings
        """
        built_strings = [
            builder.CreateString(string)
            for string in strings
        ]

        builder.StartVector(4, len(built_strings), 4)
        for built_string in reversed(built_strings):
            builder.PrependUOffsetTRelative(built_string)
        return builder.EndVector(len(built_strings))

    def serialize(self):
        """
        Builds a flatbuffer from the :class:`NDI_Object` instance.

        :rtype: bytearray
        """
        builder = flatbuffers.Builder(0)
        ndi_object = self._build(builder)
        builder.Finish(ndi_object)
        return builder.Output()

    def __eq__(self, ndi_object):
        return self.serialize() == ndi_object.serialize()
