"""
Probe Type Module
===================
Contains the ProbeType mapping of sequential integers to str type representations. Inverse of the ProbeType generated by `ndi_schema<https://>`_.
"""


# TODO: make immutable somehow
ProbeType = {
    0: 'ntrode',
    1: 'electrode',
    2: 'patch',
    3: 'patch_vm',
    4: 'patch_i',
    5: 'patch_attached',
    6: 'sharp',
    7: 'sharp_vm',
    8: 'sharp_i',
    9: 'wide_field_imaging',
    10: 'two_photon_imaging',
    11: 'one_photon_imaging',
    12: 'brightfield_imaging',
    13: 'lick_spout',
    14: 'intraoral_cannula',
    15: 'reward_well',
    16: 'stimulator'
}
