"""
Probe Type Module
===================
Contains the ProbeType mapping of sequential integers to str type representations. Inverse of the ProbeType generated by `ndi_schema<https://>`_.
"""
from .schema.ProbeType import ProbeType as ProbeType_schema
from .utils import generate_tuple_analog


ProbeType = generate_tuple_analog(ProbeType_schema)
