"""
Probe Type Module
===================
Contains the ProbeType mapping of sequential integers to str type representations. Inverse of the ProbeType generated by `ndi_schema<https://>`_.
"""

ProbeType = (
    'ntrode',
    'electrode',
    'patch',
    'patch_vm',
    'patch_i',
    'patch_attached',
    'sharp',
    'sharp_vm',
    'sharp_i',
    'wide_field_imaging',
    'two_photon_imaging',
    'one_photon_imaging',
    'brightfield_imaging',
    'lick_spout',
    'intraoral_cannula',
    'reward_well',
    'stimulator'
)
