from __future__ import annotations
import ndi.types as T
from .ndi_object import NDI_Object
import ndi.schema.Probe as build_probe
from ndi.schema.ProbeType import ProbeType as build_probe_type
from .probe_type import ProbeType


class Probe(NDI_Object):
    """
    A flatbuffer interface for probes.

    .. currentmodule:: ndi.ndi_object

    Inherits from the :class:`NDI_Object` abstract class.
    """

    def __init__(
        self,
        name: str,
        reference: int,
        type_: str,
        id_: T.NdiId = None,
        daq_system_id: T.NdiId = None
    ) -> None:
        """Probe constructor: initializes with fields defined in `ndi_schema <https://>`_'s Probe table. For use when creating a new Probe instance from scratch.
        ::
            new_probe = Probe(**fields)

        :param name:
        :type name: str
        :param reference:
        :type reference: int
        :param type_:
        :type type_: str
        :param id_: defaults to None
        :type id_: str, optional
        :param daq_system_id: defaults to ''
        :type daq_system_id: str, optional
        :raises TypeError: When *type_* is not from the list of :mod:`ndi.probe_type`.
        """
        super().__init__(id_)
        self.name = name
        self.reference = reference
        if type_ in ProbeType:
            self.type = type_
        else:
            raise TypeError(f'Type must be in {ProbeType}')
        self.daq_system_id = daq_system_id

    # Flatbuffer Methods
    @classmethod
    def from_flatbuffer(cls, flatbuffer: bytes) -> Probe:
        """Alternate Probe constructor. For use whan initializing from a flatbuffer bytearray.
        ::
            reconstructed_probe = Probe.from_flatbuffer(fb)

        :type flatbuffer: bytearray

        .. currentmodule:: ndi.probe

        :rtype: :class:`Probe`
        """
        probe = build_probe.Probe.GetRootAsProbe(flatbuffer, 0)
        return cls._reconstruct(probe)

    @classmethod
    def _reconstruct(cls, probe: T.Probe_schema) -> Probe:
        """Alternate Probe constructor. For use whan initializing from a flatbuffer generated class instance.

        :param probe: Probe object created from class generated by `ndi_schema<https://>`_
        :type probe: ndi.schema.Probe.Probe

        .. currentmodule:: ndi.probe

        :rtype: :class:`Probe`
        """
        return cls(
            id_=T.NdiId(probe.Id().decode('utf8')),
            name=probe.Name().decode('utf8'),
            reference=probe.Reference(),
            type_=ProbeType[probe.Type()],
            daq_system_id=T.NdiId(probe.DaqSystemId().decode('utf8'))
        )

    def _build(self, builder: T.Builder) -> T.BuildOffset:
        """.. currentmodule:: ndi.ndi_object

        Called in NDI_Object.serialize() as part of flatbuffer bytearray generation from Probe instance.

        :param builder: Builder class in flatbuffers module.
        :type builder: flatbuffers.Builder
        """
        id_ = builder.CreateString(self.id)
        name = builder.CreateString(self.name)
        daq_system_id = builder.CreateString(self.daq_system_id)

        build_probe.ProbeStart(builder)
        build_probe.ProbeAddId(builder, id_)
        build_probe.ProbeAddName(builder, name)
        build_probe.ProbeAddReference(builder, self.reference)
        build_probe.ProbeAddType(builder, getattr(build_probe_type, self.type))
        build_probe.ProbeAddDaqSystemId(builder, daq_system_id)
        return build_probe.ProbeEnd(builder)
