import unittest
from ndi.session.dir import Dir as SessionDir
import tempfile
import shutil
import os

class TestBuildSession(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.session_name = 'test_session_build'
        os.makedirs(os.path.join(self.temp_dir, self.session_name))

    def tearDown(self):
        shutil.rmtree(self.temp_dir)

    def test_build_session(self):
        """
        Port of ndi.unittest.session.buildSession.
        """
        session = SessionDir(self.session_name, os.path.join(self.temp_dir, self.session_name))
        self.assertIsInstance(session, SessionDir)
        # Session ID is generated by IDO and won't match the name directly
        self.assertIsNotNone(session.id())
        self.assertIsInstance(session.id(), str)
        # Verify reference matches input
        self.assertEqual(session.reference, self.session_name)

if __name__ == '__main__':
    unittest.main()
