import unittest
from ndi.session.dir import Dir as SessionDir
import tempfile
import shutil
import os

class TestSessionBuild(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        self.session_name = 'mysession'

    def tearDown(self):
        shutil.rmtree(self.temp_dir)

    def test_session_instantiation(self):
        """
        Tests the basic instantiation of a Session object, mimicking ndi.unittest.session.testSessionBuild.
        """
        session_path = os.path.join(self.temp_dir, self.session_name)
        os.makedirs(session_path)

        # Test creation with valid path
        session = SessionDir(self.session_name, session_path)
        self.assertIsInstance(session, SessionDir)

        # SessionDir stores the session path
        self.assertEqual(session.path, session_path)

        # Session ID is generated by IDO, so we just check it exists
        self.assertIsNotNone(session.id())

if __name__ == '__main__':
    unittest.main()
