# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class Document(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDocument(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Document()
        x.Init(buf, n + offset)
        return x

    # Document
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Document
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Document
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DocumentStart(builder): builder.StartObject(2)
def DocumentAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def DocumentAddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def DocumentEnd(builder): return builder.EndObject()
